### ISSUE TITLE
Harmonization IndexError

### ISSUE THREAD

**Issue by pipponino** [tohinz/ConSinGAN#12]
Hi, when I try to execute the follwing command:

`python main_train.py --gpu 0 --train_mode harmonization --train_stages 3 --min_size 120 --lrelu_alpha 0.3 --niter 1000 --batch_norm --input_name Images/oddConSinGan/good/2.png --naive_img Images/oddConSinGan/hor/8.png`

I get the following error:

```
Training model (TrainedModels/2/2020_07_26_16_02_44_harmonization_train_depth_3_lr_scale_0.1_BN_act_lrelu_0.3)
Training model with the following parameters:
    number of stages: 3
    number of concurrently trained stages: 3
    learning rate scaling: 0.1
    non-linearity: lrelu
Traceback (most recent call last):
  File "main_train.py", line 113, in <module>
    train(opt)
  File "/home/me/ConSinGAN/ConSinGAN/training_harmonization_editing.py", line 22, in train
    real = functions.read_image(opt)
  File "/home/me/ConSinGAN/ConSinGAN/functions.py", line 130, in read_image
    x = np2torch(x,opt)
  File "/home/me/ConSinGAN/ConSinGAN/functions.py", line 144, in np2torch
    x = x[:,:,:,None]
IndexError: too many indices for array
```

How can I solve? Thanks

**Comment by tohinz** [comment]
Hi,
it seems something goes wrong when reading your --naive_img.
Can you print the shape of the image after the image is loaded (so `print(x.shape)` after `x = img.imread('%s' % (opt.input_name))`)?
It should have three dimensions (width, height, channels). If the image you're loading is grayscale (black-white only) the loaded array would only have two dimensions (width, height) in which case you would have to convert the image to RGB format first before continuing.

**Comment by pipponino** [comment]
Yes, the error was about the RGB/gray format. Really thank you.
I know this problem is not related to this issue and I'm going to close it soon, but now I'm getting this:

```
Traceback (most recent call last):
  File "main_train.py", line 113, in <module>
    train(opt)
  File "/home/me/ConSinGAN/ConSinGAN/training_harmonization_editing.py", line 22, in train
    real = functions.read_image(opt)
  File "/home/me/ConSinGAN/ConSinGAN/functions.py", line 132, in read_image
    x = np2torch(x,opt)
  File "/home/me/ConSinGAN/ConSinGAN/functions.py", line 155, in np2torch
    x = x.type(torch.cuda.FloatTensor) if not(opt.not_cuda) else x.type(torch.FloatTensor)
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.
```

How could I solve?

**Comment by tohinz** [comment]
Do you have an NVIDIA GPU on your computer or only CPU?
If you have a GPU I don't know how to fix this error as I don't know what the ATen_cuda library is. Reinstalling PyTorch from scratch via pip or conda should fix this I would hope (make sure you install it for the correct CUDA version you have on your system).
If you don't have a GPU you can add the flag `--not_cuda` to run everything on CPU but this will be a lot slower. Also, to be honest, I'm not 100% sure if I have everything running on CPU, sometimes I might have just put tensors on GPU directly without checking for the `--not_cuda` flag. In this case you will get an error that a tensor was expected on a different device, so you might have to fix a couple of lines to make tensors be on CPU instead of the GPU (you'll usually only have to change `torch.cuda.FloatTensor` to `torch.FloatTensor` or add `.to(opt.device)` or `.to("cpu")` to any tensors/models).

**Comment by pipponino** [comment]
The `--not_cuda` flag seems to be working.
Thank you again!!
